version: "3.10"

services:
  container:
    container_name: container
    build: ..
    entrypoint: [
       "pytest"
    ]
    volumes:
      - ./dev/:/Reports/
      - ./dev/:/Logs/
    networks:
      selenium_net: { }

networks:
  selenium_net:
    driver: bridge

# sudo docker-compose up --build --abort-on-container-exit --remove-orphans

