name: Set up Python & Install dependencies from conda

on: [push]

jobs:
  build:
    name: Test with pytest
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: step 1
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
      #- uses: actions/upload-artifact@v3
        with:
          activate-environment: PytestFrameworkEnv
          environment-file: Config/environment.yml
          auto-activate-base: false
          #name: pytest-results
          #path: Reports/PytestHtmlReport/report.html
      - run: |
          conda info
          conda list
          conda env list
          python -m pytest -v -rs --html=Reports/PytestHtmlReport/report.html --self-contained-html

      - name: step 2
      - uses: actions/upload-artifact@v3
        with:
          name: pytest-results
          path: Reports/PytestHtmlReport/report.html